# Generated by Django 6.0.3 on 2026-03-06 18:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters')])),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('resting_heart_rate', models.PositiveIntegerField(blank=True, help_text='Beats per minute (BPM)', null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='Systolic Blood Pressure (mmHg)', null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='Diastolic Blood Pressure (mmHg)', null=True)),
                ('fasting_blood_sugar', models.FloatField(blank=True, help_text='Fasting Blood Sugar (mg/dL)', null=True)),
                ('total_cholesterol', models.FloatField(blank=True, help_text='Total Cholesterol (mg/dL)', null=True)),
                ('vitamin_deficiency', models.JSONField(blank=True, default=list, help_text='List of vitamin deficiencies')),
                ('smoking_status', models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('former', 'Former Smoker')], max_length=10, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('none', 'None'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True)),
                ('exercise_frequency', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True)),
                ('diet_type', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='myapp_user_email_5d02ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='myapp_user_name_eeb9de_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='myapp_user_date_jo_66ad39_idx'),
        ),
    ]
