# Generated by Django 6.0.3 on 2026-03-08 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='myapp_user_date_jo_66ad39_idx',
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='diastolic_bp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non Vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='fasting_blood_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='resting_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('former', 'Former')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='systolic_bp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='total_cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='vitamin_deficiency',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
