# Generated by Django 4.2.11 on 2026-03-03 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('smoking_status', models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('former', 'Former Smoker')], max_length=10, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('none', 'None'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True)),
                ('exercise_frequency', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True)),
                ('diet_type', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
