# Generated by Django 4.2.11 on 2026-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='diastolic_bp',
            field=models.PositiveIntegerField(blank=True, help_text='Diastolic Blood Pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='fasting_blood_sugar',
            field=models.FloatField(blank=True, help_text='Fasting Blood Sugar (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='resting_heart_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Beats per minute (BPM)', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='systolic_bp',
            field=models.PositiveIntegerField(blank=True, help_text='Systolic Blood Pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='total_cholesterol',
            field=models.FloatField(blank=True, help_text='Total Cholesterol (mg/dL)', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='vitamin_deficiency',
            field=models.JSONField(blank=True, default=list, help_text='List of vitamin deficiencies'),
        ),
    ]
